Feature: Convert PHPUnit tests to Pest
spatie/image-optimizer pull request #167
Opened 2022-05-09 16:57 UTC by mansoorkhan96

Hi 👋

This pull request converts PHPUnit tests to Pest. 

Thanks for the amazing work, Team Spatie.

2022-05-09 22:18 UTC, freekmurze requested changes
Very nice! I only got a few nitpicks.

2022-05-09 22:18 UTC, freekmurze commented on tests/ArrayLogger.php
> +    public function emergency(string|\Stringable $message, array $context = []): void
Could you import `Stringable`?

2022-05-09 22:18 UTC, freekmurze commented on tests/ImageTest.php
> +it('will throw an exception when given a non existing file', fn () => new Image('non existing file'))
Let's use a normal function instead of a short closure here.

2022-05-10 05:02 UTC, mansoorkhan96 commented on tests/ArrayLogger.php
> +    public function emergency(string|\Stringable $message, array $context = []): void
Done 👍

2022-05-10 05:03 UTC, mansoorkhan96 commented
Hey, @freekmurze I have updated the PR.

2022-05-10 06:35 UTC, freekmurze commented
It seems like every tests is failing. Please check locally and push a fix.

2022-05-10 08:15 UTC, mansoorkhan96 commented
Changes description:

- Removed type hinting for `$message` argument in `ArrayLogger.php` for backward compatibility tests.
- Updated expectations in `OptimizerTest` to be in Unix style. (Apologies, I am on windows and did not notice this issue).
- Replaced short closure functions with normal functions for backward compatibility tests.

2022-05-11 07:53 UTC, mansoorkhan96 commented
Hey, Sir @freekmurze 

Does this require further changes? Please let me know when you have time :)

Thanks.

2022-05-11 09:16 UTC, merged

2022-05-11 09:16 UTC, freekmurze commented
Looks good, thanks!